In [1]:
import pandas as pd

In [ ]:
df_museu = pd.read_csv('/MetObjects.csv', low_memory=False)

In [5]:
df_museu.head()

,Object Number,Is Highlight,Is Public Domain,Object ID,Department,Object Name,Title,Culture,Period,Dynasty,...,Subregion,Locale,Locus,Excavation,River,Classification,Rights and Reproduction,Link Resource,Metadata Date,Repository
0,1979.486.1,False,False,1,American Decorative Arts,Coin,One-dollar Liberty Head Coin,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Metal,NaN,http://www.metmuseum.org/art/collection/search/1,4/3/2017 8:00:08 AM,"Metropolitan Museum of Art, New York, NY"
1,1980.264.5,False,False,2,American Decorative Arts,Coin,Ten-dollar Liberty Head Coin,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Metal,NaN,http://www.metmuseum.org/art/collection/search/2,4/3/2017 8:00:08 AM,"Metropolitan Museum of Art, New York, NY"
2,67.265.9,False,False,3,American Decorative Arts,Coin,Two-and-a-Half Dollar Coin,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Metal,NaN,http://www.metmuseum.org/art/collection/search/3,4/3/2017 8:00:08 AM,"Metropolitan Museum of Art, New York, NY"
3,67.265.10,False,False,4,American Decorative Arts,Coin,Two-and-a-Half Dollar Coin,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Metal,NaN,http://www.metmuseum.org/art/collection/search/4,4/3/2017 8:00:08 AM,"Metropolitan Museum of Art, New York, NY"
4,67.265.11,False,False,5,American Decorative Arts,Coin,Two-and-a-Half Dollar Coin,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Metal,NaN,http://www.metmuseum.org/art/collection/search/5,4/3/2017 8:00:08 AM,"Metropolitan Museum of Art, New York, NY"

In [7]:
print(f"total de obras: {df_museu.shape[0]} e total de informação: {df_museu.shape[1]}")

total de obras: 448203 e total de informação: 43

In [10]:
colunas_uteis = [
    'Department',
    'Object Name',
    'Title',
    'Artist Display Name',
    'Object End Date'
]

In [11]:
df_reduzido = df_museu[colunas_uteis].copy()

In [15]:
df_limpo = df_reduzido.dropna(subset=['Artist Display Name'])

In [20]:
df_limpo.head()

,Department,Object Name,Title,Artist Display Name,Object End Date
0,American Decorative Arts,Coin,One-dollar Liberty Head Coin,James Barton Longacre,1853
1,American Decorative Arts,Coin,Ten-dollar Liberty Head Coin,Christian Gobrecht,1901
9,American Decorative Arts,Coin,Two-and-a-half-dollar Indian Head Coin,Bela Lyon Pratt,1912
10,American Decorative Arts,Coin,Two-and-a-half-dollar Liberty Head Coin,Christian Gobrecht,1907
11,American Decorative Arts,Coin,Twenty-dollar Liberty Head Coin,James Barton Longacre,1876

In [22]:
df_limpo.to_csv('obras_met_limpo.csv', index=False)